<?php

namespace IUT\NuptiasBundle\Repository;

/**
 * DecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecoRepository extends \Doctrine\ORM\EntityRepository
{
}
