<?php

namespace IUT\NuptiasBundle\Repository;

/**
 * DJRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DJRepository extends \Doctrine\ORM\EntityRepository
{
}
