iut_nuptias:
    resource: "@IUTNuptiasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

fos_user_security_login:
    path: /inscription/client
    defaults: { _controller: IUTNuptiasBundle:RegistrationClient:register }

fos_user_security_logout:
    path: /deconnexion
    defaults: { _controller: FOSUserBundle:Security:logout }

admin_registration:
    path:  /inscription/admin
    defaults: { _controller: IUTNuptiasBundle:RegistrationAdmin:register }

client_registration:
    path:  /inscription/client
    defaults: { _controller: IUTNuptiasBundle:RegistrationClient:register }

prestataire_registration:
    path:  /inscription/prestataire
    defaults: { _controller: IUTNuptiasBundle:RegistrationPrestataire:register }
