iut_nuptias:
    resource: "@IUTNuptiasBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /

fos_user_registration_register:
    path:      /inscription
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_security_login:
    path: /inscription
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_logout:
    path: /deconnexion
    defaults: { _controller: FOSUserBundle:Security:logout }
