iut_nuptias_home:
    path:     /
    defaults: { _controller: IUTNuptiasBundle:Nuptias:index }
#home à supprimer
iut_nuptias_accueil:
    path:     /accueil
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:index

iut_nuptias_packs:
    path:     /packs
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:pack

iut_nuptias_dashBoard:
    path:    /dashboard/{id}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:DashBoard
        id: 0
    requirements:
        id:   \d*

iut_nuptias_organisation:
    path:    /organisation
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:organisation

iut_nuptias_invites:
    path:    /organisation/invites/{id_mariage}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:invites
        id_mariage: 0
    requirements:
        id_mariage:   \d*

iut_nuptias_mariage:
    path:    /organisation/mariage/{pack}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:mariage
        pack: "All"

iut_nuptias_delete_mariage:
    path: /suppression/mariage/{id}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:deleteMariage
    requirements:
        id:   \d*

iut_nuptias_delete_invite:
    path: /suppression/invite/{id_mariage}/{id_invite}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:deleteInvite
        id_mariage: 0
        id_invite: 0
    requirements:
        id_mariage:   \d*
        id_invite:    \d*

iut_nuptias_send_invite:
    path: /organisation/invites/send/{id_mariage}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:sendInvite
        id_mariage: 0
    requirements:
        id_mariage:   \d*

iut_nuptias_choix_service:
    path: /service/choix
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:choixService

iut_nuptias_create_service:
    path: /service/creation
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:createService

iut_nuptias_edit_service:
    path: /service/modification
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:editService

iut_nuptias_delete_service:
    path: /service/suppression
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:deleteService

iut_nuptias_service:
    path: /service/gestion
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:service

iut_nuptias_invite_reponse:
    path: /organisation/invites/reponce/{id_mariage}/{id_invite}/{id_reponse}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:reponse
    requirements:
        id_mariage: \d*
        id_invite:  \d*
        id_reponse: \d*

iut_nuptias_affiche_services:
    path: /service/affichage
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:afficheServices

iut_nuptias_add_service_client:
    path: /service/ajouter
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:addService