iut_nuptias_home:
    path:     /
    defaults: { _controller: IUTNuptiasBundle:Nuptias:index }
#home à supprimer
iut_nuptias_accueil:
    path:     /accueil
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:index

iut_nuptias_packs:
    path:     /packs
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:pack

iut_nuptias_dashBoard:
    path:    /dashboard/{id}
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:DashBoard
        id: 0
    requirements:
        year:   \d*

iut_nuptias_organisation:
    path:    /organisation
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:organisation

iut_nuptias_invites:
    path:    /organisation/invites
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:invites

iut_nuptias_mariage:
    path:    /organisation/mariage
    defaults:
        _controller: IUTNuptiasBundle:Nuptias:mariage
