iut_nuptias_home:
    path:     /
    defaults: { _controller: IUTNuptiasBundle:Nuptias:index }
#home à supprimer
iut_nuptias_accueil:
    path:     /accueil
    defaults: { _controller: IUTNuptiasBundle:Nuptias:index }

iut_nuptias_packs:
    path:     /packs
    defaults: { _controller: IUTNuptiasBundle:Nuptias:pack }
